# Nome do fluxo de trabalho
name: Verificação de CI (Integração Contínua)

# Gatilhos: executa em push ou pull request para a branch 'main'
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # Nome do job
  install-dependencies:
    # Executa em uma máquina virtual Ubuntu
    runs-on: ubuntu-latest

    steps:
      # 1. Clona o repositório para a máquina virtual
      - name: Checkout do código
        uses: actions/checkout@v4

      # 2. Configura o ambiente Node.js
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # Podemos usar a versão 20.x

      # 3. Instala as dependências do projeto
      - name: Instalar dependências
        run: npm install
        
